name: Update dlc

on:
  schedule:
    - cron: '0 0 * * FRI'

jobs:

  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Download and Write
      run: |
        curl -L -o release/config/geoip.dat "https://github.com/v2ray/geoip/raw/release/geoip.dat"
        curl -L -o release/config/geosite.dat "https://github.com/v2ray/domain-list-community/raw/release/dlc.dat"
        
    - name: push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "update geoip, geosite" -a
        git push -v --progress
    
