name: Release Docker Image

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Checkout
        uses: actions/checkout@v2

      - name: Install Buildx and QEMU
        run: |
          export DOCKER_BUILDKIT=1
          docker build --platform=local -o . git://github.com/docker/buildx
          mkdir -p ~/.docker/cli-plugins
          mv buildx ~/.docker/cli-plugins/docker-buildx
          docker run --rm --privileged multiarch/qemu-user-static:latest --reset -p yes --credential yes
          docker buildx create --use --name build --node build --driver-opt network=host

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_IMAGE_PLATFORM: linux/386,linux/amd64,linux/arm/v7,linux/arm64
        run: |
          DOCKER_IMAGE_NAME=$(echo $DOCKER_USERNAME | tr '[:upper:]' '[:lower:]')/v2fly-core
          DOCKER_IMAGE_VERSION=${GITHUB_REF#refs/*/}
          docker buildx build \
            --platform "$DOCKER_IMAGE_PLATFORM" \
            --output "type=image,push=true" \
            --tag "$DOCKER_IMAGE_NAME":"$DOCKER_IMAGE_VERSION" \
            --tag "$DOCKER_IMAGE_NAME":latest \
            --file ./Dockerfile .
