name: Lint Code Base

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v2.2.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSON: false
          VALIDATE_ANSIBLE: false
