# This is a basic workflow to help you get started with Actions

name: Sign

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [released]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Invoke release signing
      - name: make it run
        run: chmod +x $GITHUB_WORKSPACE/release/requestsign_github.sh

      # Invoke release signing
      - name: make it run
        run: chmod +x $GITHUB_WORKSPACE/release/requestsign.sh

      # Invoke release signing
      - name: Invoke release signing
        env:
          SIGN_SERVICE_PASSWORD: ${{ secrets.SIGN_SERVICE_PASSWORD }}
          SIGN_SERIVCE_URL: ${{ secrets.SIGN_SERIVCE_URL }}
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        run: $GITHUB_WORKSPACE/release/requestsign_github.sh